services:
  nginx-server:
    image: 'nginx:stable-alpine'
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - php-interpreter
    # networks:
    #   - laravel-network
  php-interpreter:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php-interpreter
    volumes:
      - ./src:/var/www/html:delegated
    #ports:
    #  - "3000:9000" our base image exposes port 9000,
    # we modified conf file to listen on 9000
    # otherwise we would need this lines
   
      # depends_on:
      #   - mysql-server
      # networks:
      #   - laravel-network
  mysql-server:
    image: 'mysql:5.7'
    container_name: mysql-server
    env_file:
      - ./env/mysql.env

    # networks:
    #   - laravel-network
  composer:
    build:
     context: ./dockerfiles
     dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm-server:
