version: "3"
services:
  stories:
    build: .
    volumes:
      - stories:/app/story
    ports:
      - 80:3000
volumes:
  stories: # with this names volume data
           # persists between container starts and stops