apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32347 # if not specified, it will be assigned by k8s
  type: LoadBalancer